"""remove_objetivo_observacoes_descanso

Revision ID: ea912a878dad
Revises: 99f47ff69e56
Create Date: 2026-04-21 19:59:00.038969
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ea912a878dad'
down_revision = '99f47ff69e56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itens_rotina', 'observacoes')
    op.drop_column('itens_rotina', 'descanso_segundos')
    op.drop_column('rotinas', 'observacoes')
    op.drop_column('rotinas', 'objetivo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rotinas', sa.Column('objetivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('rotinas', sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('itens_rotina', sa.Column('descanso_segundos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('itens_rotina', sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
